import { useCallback, useState, useEffect } from "react";
import { useRouter } from "next/router";

export default function Footer() {
  return (
    <footer
      className="
            bg-dark
            bg-opacity-50
            mt-5"
    >
      <div
        className="
            bg-purple-500
            bg-opacity-60
            border
            border-gray-600
            rounded-md
            mx-auto 
            w-full 
            max-w-screen-xl 
            p-4 
            py-6 
            lg:py-8"
      >
        <div
          className="
            flex
            justify-center"
        >
          <div
            className="
                flex-col
                justify-start"
          >
            <div
              className="
                mb-6 
                ml-5
                md:mb-0
                flex
                items-center"
            >
              <img
                src="/images/logo.jpg"
                className="h-8 mr-3 mb-10"
                alt="Logo"
              />
              <span
                className="
                    self-center 
                    text-xl 
                    font-semibold 
                    whitespace-nowrap
                    mb-10"
              >
                Videogame
              </span>
            </div>
            <div
              className="
                flex
                justify-center"
            >
              <div>
                <h2
                  className="
                    mb-6 
                    ml-20
                    text-sm 
                    font-semibold 
                    text-gray-900 
                    uppercase"
                >
                  Follow us
                </h2>
                <ul
                  className="
                  text-gray-400 
                  font-medium
                  grid 
                  grid-cols-2 
                  gap-8 
                  sm:gap-6 
                  sm:grid-cols-3"
                >
                  <li>
                    <a
                      href="https://my-portfolio-lake-tau.vercel.app/"
                      className="hover:underline"
                    >
                      Portfolio
                    </a>
                  </li>
                  <li>
                    <a
                      href="https://github.com/Matias257987"
                      className="hover:underline"
                    >
                      Github
                    </a>
                  </li>
                  <li className="mb-4">
                    <a
                      href="https://www.linkedin.com/in/
                    matias-acosta-32c
                    "
                      className="hover:underline "
                    >
                      Linkedin
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <hr
          className="
            my-6 
            border-gray-500 
            sm:mx-auto 
            lg:my-8"
        />
        <div
          className="
            flex 
            items-center 
            justify-center"
        >
          <span
            className="
              text-sm 
              text-gray-500 
              sm:text-center"
          >
            © 2023{" "}
            <a
              href="https://my-portfolio-lake-tau.vercel.app/"
              className="hover:underline"
            >
              Acosta Matias™
            </a>
            . All Rights Reserved.
          </span>
        </div>
      </div>
    </footer>
  );
}
